<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Opportunity extends \App\Models\Doctrine\Opportunity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'estimated_sale' => [parent::class, 'estimated_sale', null, 16],
        "\0".parent::class."\0".'expected_closing_date' => [parent::class, 'expected_closing_date', null, 16],
        "\0".parent::class."\0".'leadOrigin' => [parent::class, 'leadOrigin', null, 16],
        "\0".parent::class."\0".'open_date' => [parent::class, 'open_date', null, 16],
        "\0".parent::class."\0".'opportunityStage' => [parent::class, 'opportunityStage', null, 16],
        "\0".parent::class."\0".'opportunityStatus' => [parent::class, 'opportunityStatus', null, 16],
        "\0".parent::class."\0".'opportunity_id' => [parent::class, 'opportunity_id', null, 16],
        "\0".parent::class."\0".'opportunity_name' => [parent::class, 'opportunity_name', null, 16],
        "\0".parent::class."\0".'person' => [parent::class, 'person', null, 16],
        "\0".parent::class."\0".'priority' => [parent::class, 'priority', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'vendor' => [parent::class, 'vendor', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'estimated_sale' => [parent::class, 'estimated_sale', null, 16],
        'expected_closing_date' => [parent::class, 'expected_closing_date', null, 16],
        'leadOrigin' => [parent::class, 'leadOrigin', null, 16],
        'open_date' => [parent::class, 'open_date', null, 16],
        'opportunityStage' => [parent::class, 'opportunityStage', null, 16],
        'opportunityStatus' => [parent::class, 'opportunityStatus', null, 16],
        'opportunity_id' => [parent::class, 'opportunity_id', null, 16],
        'opportunity_name' => [parent::class, 'opportunity_name', null, 16],
        'person' => [parent::class, 'person', null, 16],
        'priority' => [parent::class, 'priority', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'vendor' => [parent::class, 'vendor', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
