<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activity extends \App\Models\Doctrine\Activity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activity_date' => [parent::class, 'activity_date', null, 16],
        "\0".parent::class."\0".'activity_id' => [parent::class, 'activity_id', null, 16],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'duration_min' => [parent::class, 'duration_min', null, 16],
        "\0".parent::class."\0".'opportunity' => [parent::class, 'opportunity', null, 16],
        "\0".parent::class."\0".'result' => [parent::class, 'result', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'activity_date' => [parent::class, 'activity_date', null, 16],
        'activity_id' => [parent::class, 'activity_id', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'duration_min' => [parent::class, 'duration_min', null, 16],
        'opportunity' => [parent::class, 'opportunity', null, 16],
        'result' => [parent::class, 'result', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'titulo' => [parent::class, 'titulo', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
