<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Models\Doctrine\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created' => [parent::class, 'created', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'email_verified_at' => [parent::class, 'email_verified_at', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'remember_token' => [parent::class, 'remember_token', null, 16],
        "\0".parent::class."\0".'updated' => [parent::class, 'updated', null, 16],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        "\0".parent::class."\0".'usersGroup' => [parent::class, 'usersGroup', null, 16],
        'created' => [parent::class, 'created', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'email_verified_at' => [parent::class, 'email_verified_at', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'remember_token' => [parent::class, 'remember_token', null, 16],
        'updated' => [parent::class, 'updated', null, 16],
        'user_id' => [parent::class, 'user_id', null, 16],
        'username' => [parent::class, 'username', null, 16],
        'usersGroup' => [parent::class, 'usersGroup', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
