<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \App\Models\Doctrine\Person implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'birthdate' => [parent::class, 'birthdate', null, 16],
        "\0".parent::class."\0".'cep' => [parent::class, 'cep', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null, 16],
        "\0".parent::class."\0".'company_dept' => [parent::class, 'company_dept', null, 16],
        "\0".parent::class."\0".'complement' => [parent::class, 'complement', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'cpf' => [parent::class, 'cpf', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'job_position' => [parent::class, 'job_position', null, 16],
        "\0".parent::class."\0".'main_email' => [parent::class, 'main_email', null, 16],
        "\0".parent::class."\0".'main_phone' => [parent::class, 'main_phone', null, 16],
        "\0".parent::class."\0".'marital_status' => [parent::class, 'marital_status', null, 16],
        "\0".parent::class."\0".'neighborhood' => [parent::class, 'neighborhood', null, 16],
        "\0".parent::class."\0".'personRole' => [parent::class, 'personRole', null, 16],
        "\0".parent::class."\0".'person_id' => [parent::class, 'person_id', null, 16],
        "\0".parent::class."\0".'person_name' => [parent::class, 'person_name', null, 16],
        "\0".parent::class."\0".'rg' => [parent::class, 'rg', null, 16],
        "\0".parent::class."\0".'sex' => [parent::class, 'sex', null, 16],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'birthdate' => [parent::class, 'birthdate', null, 16],
        'cep' => [parent::class, 'cep', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'company' => [parent::class, 'company', null, 16],
        'company_dept' => [parent::class, 'company_dept', null, 16],
        'complement' => [parent::class, 'complement', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'cpf' => [parent::class, 'cpf', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'job_position' => [parent::class, 'job_position', null, 16],
        'main_email' => [parent::class, 'main_email', null, 16],
        'main_phone' => [parent::class, 'main_phone', null, 16],
        'marital_status' => [parent::class, 'marital_status', null, 16],
        'neighborhood' => [parent::class, 'neighborhood', null, 16],
        'personRole' => [parent::class, 'personRole', null, 16],
        'person_id' => [parent::class, 'person_id', null, 16],
        'person_name' => [parent::class, 'person_name', null, 16],
        'rg' => [parent::class, 'rg', null, 16],
        'sex' => [parent::class, 'sex', null, 16],
        'state' => [parent::class, 'state', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
