<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \App\Models\Doctrine\Company implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'cep' => [parent::class, 'cep', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'cnpj' => [parent::class, 'cnpj', null, 16],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'company_id' => [parent::class, 'company_id', null, 16],
        "\0".parent::class."\0".'company_size' => [parent::class, 'company_size', null, 16],
        "\0".parent::class."\0".'complement' => [parent::class, 'complement', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'fantasy_name' => [parent::class, 'fantasy_name', null, 16],
        "\0".parent::class."\0".'inscricao_estadual' => [parent::class, 'inscricao_estadual', null, 16],
        "\0".parent::class."\0".'inscricao_municipal' => [parent::class, 'inscricao_municipal', null, 16],
        "\0".parent::class."\0".'main_email' => [parent::class, 'main_email', null, 16],
        "\0".parent::class."\0".'main_phone' => [parent::class, 'main_phone', null, 16],
        "\0".parent::class."\0".'neighborhood' => [parent::class, 'neighborhood', null, 16],
        "\0".parent::class."\0".'social_reason' => [parent::class, 'social_reason', null, 16],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'cep' => [parent::class, 'cep', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'cnpj' => [parent::class, 'cnpj', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'company_id' => [parent::class, 'company_id', null, 16],
        'company_size' => [parent::class, 'company_size', null, 16],
        'complement' => [parent::class, 'complement', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'fantasy_name' => [parent::class, 'fantasy_name', null, 16],
        'inscricao_estadual' => [parent::class, 'inscricao_estadual', null, 16],
        'inscricao_municipal' => [parent::class, 'inscricao_municipal', null, 16],
        'main_email' => [parent::class, 'main_email', null, 16],
        'main_phone' => [parent::class, 'main_phone', null, 16],
        'neighborhood' => [parent::class, 'neighborhood', null, 16],
        'social_reason' => [parent::class, 'social_reason', null, 16],
        'state' => [parent::class, 'state', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'website' => [parent::class, 'website', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
