<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductService extends \App\Models\Doctrine\ProductService implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'category' => [parent::class, 'category', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'isTangible' => [parent::class, 'isTangible', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'product_service_id' => [parent::class, 'product_service_id', null, 16],
        "\0".parent::class."\0".'sku' => [parent::class, 'sku', null, 16],
        "\0".parent::class."\0".'taxRate' => [parent::class, 'taxRate', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'unit' => [parent::class, 'unit', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'category' => [parent::class, 'category', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'isTangible' => [parent::class, 'isTangible', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'product_service_id' => [parent::class, 'product_service_id', null, 16],
        'sku' => [parent::class, 'sku', null, 16],
        'taxRate' => [parent::class, 'taxRate', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'unit' => [parent::class, 'unit', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
