<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LeadOrigin extends \App\Models\Doctrine\LeadOrigin implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'lead_origin_id' => [parent::class, 'lead_origin_id', null, 16],
        "\0".parent::class."\0".'origin' => [parent::class, 'origin', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'lead_origin_id' => [parent::class, 'lead_origin_id', null, 16],
        'origin' => [parent::class, 'origin', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
