<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Document extends \App\Models\Doctrine\Document implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'doc_name' => [parent::class, 'doc_name', null, 16],
        "\0".parent::class."\0".'document_id' => [parent::class, 'document_id', null, 16],
        "\0".parent::class."\0".'file_path' => [parent::class, 'file_path', null, 16],
        "\0".parent::class."\0".'file_type' => [parent::class, 'file_type', null, 16],
        "\0".parent::class."\0".'filename' => [parent::class, 'filename', null, 16],
        "\0".parent::class."\0".'opportunity' => [parent::class, 'opportunity', null, 16],
        "\0".parent::class."\0".'size_bytes' => [parent::class, 'size_bytes', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'doc_name' => [parent::class, 'doc_name', null, 16],
        'document_id' => [parent::class, 'document_id', null, 16],
        'file_path' => [parent::class, 'file_path', null, 16],
        'file_type' => [parent::class, 'file_type', null, 16],
        'filename' => [parent::class, 'filename', null, 16],
        'opportunity' => [parent::class, 'opportunity', null, 16],
        'size_bytes' => [parent::class, 'size_bytes', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
